### ISSUE TITLE
ArmHf

### ISSUE THREAD

**Issue by wendigo75** [yentencoin/yenten#16]
Armhf processor are not supported in your CPUMiner.
It's an issue of the Yespowerr16 Algorithm or an issue for 32bit systems ?
Even if not so performance Armhf processor it's quite good will u implement Armhf in Linux-based CPUMiner?

**Comment by yentencoin** [comment]
What equipment are you trying to run mining on?
What miner?

The algorithm supports, you can make an assembly, but the hash will be very small.

**Comment by wendigo75** [comment]
no matter for the hashes, i've about 3 rasperry pi3+ (Ubuntu Mate) and no electricity bill.
I've an 32bit Acer Aspire one N270D with windows 7.
Both machines are unable to recompile your miner (emmtrinn.h *of course Raspberry are not Intel cpus*) antd other issues about __m128 instead __m32 (not sure it's the right quote i'm going about memory).

**Comment by wendigo75** [comment]
Thank you for support.
Googling around i found a forked working with 32bit and tested with pi3+
It works around 48 H/s.
