### ISSUE TITLE
Wallet Transactions history section is missing translations [ru-RU]

### ISSUE THREAD

**Issue by maanto** [yentencoin/yenten#19]
multiple sections of the Transactions history menu are still in English when the OS display language is set to Russian. 
Please see red highlighted areas in the screenshot attached.
Thank you.
![wallet transactions missing translations - RU](https://user-images.githubusercontent.com/5191831/89328611-807bbd00-d642-11ea-8c2a-e8743f9c0a5b.png)

**Comment by yentencoin** [comment]
Thank. We will think about it.
Often terms are better understood in English, without translation.
