### ISSUE TITLE
bitcoin_en.ts update

### ISSUE THREAD

**Issue by middlingphys** [yentencoin/yenten#36]
Following lines from "Wallet options" are not in [bitcoin_en.ts](https://github.com/yentencoin/yenten/blob/yenten-5.0.0/src/qt/locale/bitcoin_en.ts):

> What type of addresses to use ("legacy", "p2sh-segwit", or "bech32", default: "legacy")

> What type of change to use ("legacy", "p2sh-segwit", or "bech32"). Default is same as -addresstype, except when -addresstype=p2sh-segwit a native segwit output is used when sending to a native segwit address) 

Please update the file so they can be translated.

**Comment by yentencoin** [comment]
Although I tried to add translations related to issue https://github.com/yentencoin/yenten/issues/36 you raised, you have kindly solved more yourself.
Thank you for your contributions!
あなたから上げて頂いた問題#36に関して翻訳を追加しようと試みていましたが、あなたご自身に、より多くのことを解決して頂いてしまいました。
ご協力ありがとうございます！
