### ISSUE TITLE
restore crex24

### ISSUE THREAD

**Issue by ptica** [yentencoin/yenten#5]
official renegotiation with crex24 is needed,
their position as per request through support@crex24.com is:

>Hello
>
>Coin developer doesn't not respond and we will delist the coin If won't 
>get the reply.
>
>Happy Holidays,
>Crex24 Support

**Comment by yentencoin** [comment]
> official renegotiation with crex24 is needed,
> their position as per request through [support@crex24.com](mailto:support@crex24.com) is:
> 
> > Hello
> > Coin developer doesn't not respond and we will delist the coin If won't
> > get the reply.
> > Happy Holidays,
> > Crex24 Support

Thanks for the quick wallet update!
